-- User correction 2026-10-01: nationwide service area; Hattersheim remains the company location.
-- Optimistic content guards prevent overwriting concurrent editorial changes.
DO $nationwide$
DECLARE affected integer;
BEGIN
update public.services set short_text='Naturstein für Terrassen, Gartenwege, Mauern und Stufen. Wir stimmen Material, Oberfläche und Aufbau auf Ihr Vorhaben in ganz Deutschland ab.',
  long_text='Eine Natursteinterrasse, eine Natursteinmauer oder Stufen zwischen zwei Gartenebenen: Naturstein lässt sich dort einsetzen, wo Gestaltung und Nutzung zusammenpassen sollen. Loni GalaBau aus Hattersheim übernimmt Natursteinarbeiten in ganz Deutschland. Gemeinsam besprechen wir, welche Flächen Sie verändern möchten und wie sich der Stein in Ihren Garten einfügen soll. Auch Anschlüsse an vorhandene Wege, Beete und das Haus beziehen wir ein.

Granit, Sandstein, Basalt oder Kalkstein unterscheiden sich in Farbe, Struktur und Oberflächenwirkung. Entscheidend ist aber auch der konkrete Einsatz: Ein häufig genutzter Gartenweg stellt andere Anforderungen als eine Beetbegrenzung. Wir stimmen Material, Format und Bearbeitung auf Ihr Vorhaben ab. Ein Muster hilft dabei, Farben und Oberflächen im Zusammenhang mit Fassade, Pflanzen und vorhandenen Belägen zu betrachten.

Vor der Ausführung prüfen wir die Ausgangssituation und klären den vereinbarten Aufbau. Bei einer Terrasse gehören Höhen, Untergrund, Gefälle und Wasserführung zur Planung. Bei Mauern und Treppen kommen Verlauf, Übergänge und die örtlichen Bedingungen hinzu. Ob eine Konstruktion zusätzliche Planung benötigt, besprechen wir vor Beginn. So werden die sichtbare Gestaltung und die Arbeiten unter der Oberfläche gemeinsam betrachtet.

Die Kosten von Natursteinarbeiten hängen unter anderem vom Stein, der Fläche, Zuschnitten, der Vorbereitung und der Erreichbarkeit ab. Beschreiben Sie uns, ob eine neue Fläche entstehen oder ein vorhandener Bereich umgestaltet werden soll. Fotos, ungefähre Maße und Angaben zur Zufahrt erleichtern das erste Gespräch. Anschließend stimmen wir Material und Leistungsumfang ab und erstellen ein Angebot für die besprochenen Arbeiten.',
  meta_title='Natursteinarbeiten deutschlandweit | Loni GalaBau',
  meta_description='Natursteinarbeiten deutschlandweit: Terrassen, Wege, Mauern und Stufen. Material und Aufbau persönlich abstimmen. Sitz in Hattersheim bei Frankfurt.',
  geo_focus='Deutschlandweit' where slug='natursteinarbeiten' and short_text is not distinct from 'Naturstein für Terrassen, Gartenwege, Mauern und Stufen. Wir stimmen Material, Oberfläche und Aufbau auf Ihr Vorhaben in Hattersheim und im Rhein-Main-Gebiet ab.' and long_text is not distinct from 'Eine Natursteinterrasse, eine Natursteinmauer oder Stufen zwischen zwei Gartenebenen: Naturstein lässt sich dort einsetzen, wo Gestaltung und Nutzung zusammenpassen sollen. Loni GalaBau aus Hattersheim übernimmt Natursteinarbeiten im Rhein-Main-Gebiet. Gemeinsam besprechen wir, welche Flächen Sie verändern möchten und wie sich der Stein in Ihren Garten einfügen soll. Auch Anschlüsse an vorhandene Wege, Beete und das Haus beziehen wir ein.

Granit, Sandstein, Basalt oder Kalkstein unterscheiden sich in Farbe, Struktur und Oberflächenwirkung. Entscheidend ist aber auch der konkrete Einsatz: Ein häufig genutzter Gartenweg stellt andere Anforderungen als eine Beetbegrenzung. Wir stimmen Material, Format und Bearbeitung auf Ihr Vorhaben ab. Ein Muster hilft dabei, Farben und Oberflächen im Zusammenhang mit Fassade, Pflanzen und vorhandenen Belägen zu betrachten.

Vor der Ausführung prüfen wir die Ausgangssituation und klären den vereinbarten Aufbau. Bei einer Terrasse gehören Höhen, Untergrund, Gefälle und Wasserführung zur Planung. Bei Mauern und Treppen kommen Verlauf, Übergänge und die örtlichen Bedingungen hinzu. Ob eine Konstruktion zusätzliche Planung benötigt, besprechen wir vor Beginn. So werden die sichtbare Gestaltung und die Arbeiten unter der Oberfläche gemeinsam betrachtet.

Die Kosten von Natursteinarbeiten hängen unter anderem vom Stein, der Fläche, Zuschnitten, der Vorbereitung und der Erreichbarkeit ab. Beschreiben Sie uns, ob eine neue Fläche entstehen oder ein vorhandener Bereich umgestaltet werden soll. Fotos, ungefähre Maße und Angaben zur Zufahrt erleichtern das erste Gespräch. Anschließend stimmen wir Material und Leistungsumfang ab und erstellen ein Angebot für die besprochenen Arbeiten.' and meta_title is not distinct from 'Natursteinarbeiten in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Natursteinarbeiten in Hattersheim und Rhein-Main: Terrassen, Wege, Mauern und Stufen. Material und Aufbau persönlich abstimmen. Projekt anfragen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: natursteinarbeiten'; END IF;
update public.services set short_text='Einen Garten neu anlegen oder vorhandene Bereiche umgestalten: Wir verbinden Wege, Terrasse, Rasen und Pflanzen zu einem Garten, der zu Ihrem Alltag passt.',
  long_text='Sie möchten einen vorhandenen Garten umgestalten oder nach einem Neubau einen Garten anlegen lassen? Loni GalaBau begleitet Ihre Gartengestaltung in ganz Deutschland. Am Anfang steht die Nutzung: Wo möchten Sie sitzen, wie bewegen Sie sich durch den Garten und welche Bereiche sollen frei bleiben? Aus Ihren Wünschen und den Bedingungen des Grundstücks entsteht eine passende Aufteilung.

Zur Gartenplanung gehören mehr als Pflanzen und Beläge. Wir betrachten vorhandene Höhen, sonnige und schattige Bereiche, Zugänge und Anschlüsse an das Haus. Terrasse, Gartenwege, Rasen und Beete sollen sinnvoll zusammenarbeiten. Bestehende Pflanzen oder gut erhaltene Flächen können dabei Teil der Gestaltung bleiben. Für eine weitergehende Planung beziehen wir bei Bedarf unseren Planungspartner ein und stimmen den Umfang mit Ihnen ab.

Ein moderner, pflegeleichter Garten beginnt mit Entscheidungen, die zum Alltag passen. Wie viel Zeit möchten Sie für Rasen und Beete aufbringen? Welche Wege werden häufig genutzt? Wir besprechen Pflanzenauswahl, Flächenaufteilung und Materialien mit Blick auf Standort und Pflegeaufwand. Pflegeleicht bedeutet dabei nicht pflegefrei. Auch Bewässerung, Sichtschutz und die Ableitung von Regenwasser lassen sich von Anfang an berücksichtigen.

Die Umsetzung kann den gesamten Außenbereich oder einzelne Gartenbereiche umfassen. Wenn Sie in Bauabschnitten arbeiten möchten, besprechen wir die Reihenfolge und notwendige Vorarbeiten. Für ein Angebot sind Fläche, Bestand, Materialwünsche, Zufahrt und gewünschter Leistungsumfang wichtig. Bringen Sie gern Fotos, eine Skizze oder Beispiele mit. Gemeinsam klären wir, welche Ideen zu Ihrem Grundstück passen und wie daraus ein konkretes Gartenprojekt wird.',
  meta_title='Gartengestaltung deutschlandweit | Loni GalaBau',
  meta_description='Gartengestaltung deutschlandweit: Garten neu anlegen oder umgestalten, Terrasse, Wege und Pflanzen abstimmen. Ihr Vorhaben mit Loni GalaBau besprechen.',
  geo_focus='Deutschlandweit' where slug='gartengestaltung' and short_text is not distinct from 'Einen Garten neu anlegen oder vorhandene Bereiche umgestalten: Wir verbinden Wege, Terrasse, Rasen und Pflanzen zu einem Garten, der zu Ihrem Alltag passt.' and long_text is not distinct from 'Sie möchten einen vorhandenen Garten umgestalten oder nach einem Neubau einen Garten anlegen lassen? Loni GalaBau begleitet Ihre Gartengestaltung in Hattersheim und im Rhein-Main-Gebiet. Am Anfang steht die Nutzung: Wo möchten Sie sitzen, wie bewegen Sie sich durch den Garten und welche Bereiche sollen frei bleiben? Aus Ihren Wünschen und den Bedingungen des Grundstücks entsteht eine passende Aufteilung.

Zur Gartenplanung gehören mehr als Pflanzen und Beläge. Wir betrachten vorhandene Höhen, sonnige und schattige Bereiche, Zugänge und Anschlüsse an das Haus. Terrasse, Gartenwege, Rasen und Beete sollen sinnvoll zusammenarbeiten. Bestehende Pflanzen oder gut erhaltene Flächen können dabei Teil der Gestaltung bleiben. Für eine weitergehende Planung beziehen wir bei Bedarf unseren Planungspartner ein und stimmen den Umfang mit Ihnen ab.

Ein moderner, pflegeleichter Garten beginnt mit Entscheidungen, die zum Alltag passen. Wie viel Zeit möchten Sie für Rasen und Beete aufbringen? Welche Wege werden häufig genutzt? Wir besprechen Pflanzenauswahl, Flächenaufteilung und Materialien mit Blick auf Standort und Pflegeaufwand. Pflegeleicht bedeutet dabei nicht pflegefrei. Auch Bewässerung, Sichtschutz und die Ableitung von Regenwasser lassen sich von Anfang an berücksichtigen.

Die Umsetzung kann den gesamten Außenbereich oder einzelne Gartenbereiche umfassen. Wenn Sie in Bauabschnitten arbeiten möchten, besprechen wir die Reihenfolge und notwendige Vorarbeiten. Für ein Angebot sind Fläche, Bestand, Materialwünsche, Zufahrt und gewünschter Leistungsumfang wichtig. Bringen Sie gern Fotos, eine Skizze oder Beispiele mit. Gemeinsam klären wir, welche Ideen zu Ihrem Grundstück passen und wie daraus ein konkretes Gartenprojekt wird.' and meta_title is not distinct from 'Gartengestaltung in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Gartengestaltung in Hattersheim und Rhein-Main: Garten neu anlegen oder umgestalten, Terrasse, Wege und Pflanzen abstimmen. Jetzt Ihr Vorhaben besprechen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: gartengestaltung'; END IF;
update public.services set short_text='Einfahrten, Terrassen und Gartenwege pflastern lassen: Wir planen Belag, Unterbau und Entwässerung zusammen und setzen die abgestimmten Arbeiten um.',
  long_text='Eine Einfahrt muss andere Belastungen aufnehmen als ein Gartenweg oder ein Sitzplatz. Für Pflasterarbeiten in ganz Deutschland stimmen wir deshalb den sichtbaren Belag und den Aufbau darunter gemeinsam ab. Loni GalaBau pflastert Einfahrten, Terrassen und Wege nach den Anforderungen Ihres Grundstücks. Dabei berücksichtigen wir auch Anschlüsse an Garage, Haustür und vorhandene Gartenflächen.

Zu Beginn klären wir, wie die Fläche genutzt werden soll. Welche Fahrzeuge befahren die Einfahrt? Soll ein Weg bequem vom Haus zum Garten führen? Welche Höhen sind bereits vorgegeben? Daraus ergeben sich wichtige Entscheidungen für Material, Unterbau und Einfassungen. Betonstein, Naturstein oder Klinker bieten unterschiedliche Formate und Gestaltungsmöglichkeiten. Oberfläche, Farbe und Verlegemuster wählen wir passend zur Umgebung und zur vereinbarten Nutzung.

Je nach Ausgangssituation gehören Rückbau, Aushub, Herstellung der Tragschicht, Randeinfassungen, Verlegung und Verfugung zum Leistungsumfang. Das Regenwasser berücksichtigen wir bei Höhen und Gefälle von Anfang an. Falls Entwässerungsrinnen oder weitere Maßnahmen erforderlich sind, stimmen wir diese mit der Pflasterfläche ab. Auch vorhandenes Pflaster können wir auf eine mögliche Wiederverwendung prüfen.

Was Pflasterarbeiten kosten, hängt nicht allein von den Quadratmetern ab. Der bestehende Untergrund, Entsorgung, Material, Zuschnitte, Einfassungen und Zufahrt beeinflussen den Aufwand. Für ein erstes Gespräch helfen Fotos, ungefähre Maße und Angaben zur späteren Belastung. Nach Klärung des Bestands erhalten Sie ein Angebot über die besprochenen Arbeiten. So können Sie nachvollziehen, welche Leistungen für Ihre neue Einfahrt, Terrasse oder Ihren Gartenweg vorgesehen sind.',
  meta_title='Pflasterarbeiten deutschlandweit | Loni GalaBau',
  meta_description='Einfahrt, Terrasse oder Gartenweg pflastern lassen – deutschlandweit. Pflasterarbeiten mit abgestimmtem Unterbau und Entwässerung bei Loni GalaBau anfragen.',
  geo_focus='Deutschlandweit' where slug='pflasterarbeiten' and short_text is not distinct from 'Einfahrten, Terrassen und Gartenwege pflastern lassen: Wir planen Belag, Unterbau und Entwässerung zusammen und setzen die abgestimmten Arbeiten um.' and long_text is not distinct from 'Eine Einfahrt muss andere Belastungen aufnehmen als ein Gartenweg oder ein Sitzplatz. Für Pflasterarbeiten in Hattersheim und im Rhein-Main-Gebiet stimmen wir deshalb den sichtbaren Belag und den Aufbau darunter gemeinsam ab. Loni GalaBau pflastert Einfahrten, Terrassen und Wege nach den Anforderungen Ihres Grundstücks. Dabei berücksichtigen wir auch Anschlüsse an Garage, Haustür und vorhandene Gartenflächen.

Zu Beginn klären wir, wie die Fläche genutzt werden soll. Welche Fahrzeuge befahren die Einfahrt? Soll ein Weg bequem vom Haus zum Garten führen? Welche Höhen sind bereits vorgegeben? Daraus ergeben sich wichtige Entscheidungen für Material, Unterbau und Einfassungen. Betonstein, Naturstein oder Klinker bieten unterschiedliche Formate und Gestaltungsmöglichkeiten. Oberfläche, Farbe und Verlegemuster wählen wir passend zur Umgebung und zur vereinbarten Nutzung.

Je nach Ausgangssituation gehören Rückbau, Aushub, Herstellung der Tragschicht, Randeinfassungen, Verlegung und Verfugung zum Leistungsumfang. Das Regenwasser berücksichtigen wir bei Höhen und Gefälle von Anfang an. Falls Entwässerungsrinnen oder weitere Maßnahmen erforderlich sind, stimmen wir diese mit der Pflasterfläche ab. Auch vorhandenes Pflaster können wir auf eine mögliche Wiederverwendung prüfen.

Was Pflasterarbeiten kosten, hängt nicht allein von den Quadratmetern ab. Der bestehende Untergrund, Entsorgung, Material, Zuschnitte, Einfassungen und Zufahrt beeinflussen den Aufwand. Für ein erstes Gespräch helfen Fotos, ungefähre Maße und Angaben zur späteren Belastung. Nach Klärung des Bestands erhalten Sie ein Angebot über die besprochenen Arbeiten. So können Sie nachvollziehen, welche Leistungen für Ihre neue Einfahrt, Terrasse oder Ihren Gartenweg vorgesehen sind.' and meta_title is not distinct from 'Pflasterarbeiten in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Einfahrt, Terrasse oder Gartenweg pflastern lassen in Hattersheim und Rhein-Main. Pflasterarbeiten mit abgestimmtem Unterbau und Entwässerung anfragen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: pflasterarbeiten'; END IF;
update public.services set short_text='Bewässerungsanlagen für Rasen und Beete: Wir planen Regner, Tropfbewässerung und Steuerung passend zu Ihren Gartenflächen und dem vorhandenen Wasseranschluss.',
  long_text='Eine Bewässerungsanlage im Garten soll die richtigen Flächen versorgen und sich verständlich bedienen lassen. Loni GalaBau plant und installiert Gartenbewässerung in ganz Deutschland. Wir betrachten Rasen, Beete und Pflanzbereiche einzeln und stimmen die Anlage auf deren Nutzung sowie den vorhandenen Wasseranschluss ab. Das ist bei einer Gartenneuanlage ebenso wichtig wie bei der Nachrüstung im Bestand.

Rasenflächen lassen sich mit passend angeordneten Regnern bewässern; für viele Pflanzbereiche kommen Tropfleitungen infrage. Welche Kombination sinnvoll ist, hängt von Form und Größe der Flächen, der Bepflanzung und den örtlichen Bedingungen ab. Wir besprechen, welche Bereiche gemeinsam versorgt werden können und wo eine getrennte Steuerung sinnvoll ist. Wege, Sitzplätze und andere Flächen beziehen wir bei der Anordnung mit ein.

Vor der Installation klären wir Leitungswege, Anschlussmöglichkeiten und die gewünschte Bedienung. Eine zeitgesteuerte Bewässerung, eine Steuerung per App oder ergänzende Sensoren kommen je nach Vorhaben infrage. Umfang und Ausstattung werden vor der Ausführung vereinbart. Eine automatische Anlage ersetzt dabei nicht die passende Einstellung: Wetter, Jahreszeit und Pflanzenbedarf müssen bei der Nutzung berücksichtigt werden.

Bei bestehenden Gärten besprechen wir auch, wo Leitungen verlegt werden können und welche Flächen anschließend wiederherzustellen sind. Der Aufwand ergibt sich unter anderem aus Flächengröße, Zahl der Bewässerungsbereiche, Anschlussbedingungen und Steuerung. Für Ihre Anfrage helfen ein Grundstücksplan oder eine Skizze, Fotos und Angaben zum Wasseranschluss. Nach der Installation erklären wir die vereinbarte Bedienung und besprechen Pflege, Kontrolle und die Vorbereitung auf die kalte Jahreszeit.',
  meta_title='Bewässerungsanlagen deutschlandweit | Loni GalaBau',
  meta_description='Gartenbewässerung deutschlandweit planen und installieren lassen: Regner und Tropfbewässerung passend zu Rasen, Beeten und Grundstück. Loni GalaBau.',
  geo_focus='Deutschlandweit' where slug='bewaesserungsanlagen' and short_text is not distinct from 'Bewässerungsanlagen für Rasen und Beete: Wir planen Regner, Tropfbewässerung und Steuerung passend zu Ihren Gartenflächen und dem vorhandenen Wasseranschluss.' and long_text is not distinct from 'Eine Bewässerungsanlage im Garten soll die richtigen Flächen versorgen und sich verständlich bedienen lassen. Loni GalaBau plant und installiert Gartenbewässerung in Hattersheim und im Rhein-Main-Gebiet. Wir betrachten Rasen, Beete und Pflanzbereiche einzeln und stimmen die Anlage auf deren Nutzung sowie den vorhandenen Wasseranschluss ab. Das ist bei einer Gartenneuanlage ebenso wichtig wie bei der Nachrüstung im Bestand.

Rasenflächen lassen sich mit passend angeordneten Regnern bewässern; für viele Pflanzbereiche kommen Tropfleitungen infrage. Welche Kombination sinnvoll ist, hängt von Form und Größe der Flächen, der Bepflanzung und den örtlichen Bedingungen ab. Wir besprechen, welche Bereiche gemeinsam versorgt werden können und wo eine getrennte Steuerung sinnvoll ist. Wege, Sitzplätze und andere Flächen beziehen wir bei der Anordnung mit ein.

Vor der Installation klären wir Leitungswege, Anschlussmöglichkeiten und die gewünschte Bedienung. Eine zeitgesteuerte Bewässerung, eine Steuerung per App oder ergänzende Sensoren kommen je nach Vorhaben infrage. Umfang und Ausstattung werden vor der Ausführung vereinbart. Eine automatische Anlage ersetzt dabei nicht die passende Einstellung: Wetter, Jahreszeit und Pflanzenbedarf müssen bei der Nutzung berücksichtigt werden.

Bei bestehenden Gärten besprechen wir auch, wo Leitungen verlegt werden können und welche Flächen anschließend wiederherzustellen sind. Der Aufwand ergibt sich unter anderem aus Flächengröße, Zahl der Bewässerungsbereiche, Anschlussbedingungen und Steuerung. Für Ihre Anfrage helfen ein Grundstücksplan oder eine Skizze, Fotos und Angaben zum Wasseranschluss. Nach der Installation erklären wir die vereinbarte Bedienung und besprechen Pflege, Kontrolle und die Vorbereitung auf die kalte Jahreszeit.' and meta_title is not distinct from 'Bewässerungsanlagen in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Bewässerungsanlage für Ihren Garten in Hattersheim und Rhein-Main planen lassen: Rasen, Beete, Regner und Tropfbewässerung passend zum Grundstück.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: bewaesserungsanlagen'; END IF;
update public.services set short_text='Zaunbau, Gartentore und Sichtschutz für Ihr Grundstück. Wir stimmen Material, Höhe, Verlauf und Montage auf Ihre Wünsche und die Gegebenheiten vor Ort ab.',
  long_text='Ein Gartenzaun markiert Grenzen, ein Tor ordnet den Zugang und ein Sichtschutz schafft einen geschützteren Sitzplatz. Loni GalaBau übernimmt Zaunarbeiten und Zaunbau in ganz Deutschland. Gemeinsam klären wir, welche Aufgabe Ihre Anlage erfüllen soll: eine offene Einfriedung, mehr Privatsphäre oder eine Kombination mit einem passenden Gartentor.

Holz, Metall, Doppelstabmatten oder Gabionen wirken unterschiedlich und stellen unterschiedliche Anforderungen an Aufbau und Pflege. Wir besprechen Material, Farbe und Höhe im Zusammenhang mit Haus, Garten und angrenzenden Flächen. Auch der Verlauf ist wichtig: Ein Grundstück mit Gefälle benötigt andere Übergänge als eine ebene Fläche. Bestehende Mauern, Bäume und Wege werden bei der Planung berücksichtigt.

Bevor Sie einen Zaun montieren lassen, sollten Grundstücksgrenzen und erforderliche Abstimmungen geklärt sein. Wir sehen uns die vorgesehenen Standorte der Pfosten und den Untergrund an. Bei Toren besprechen wir Durchgangsbreite, Öffnungsrichtung und die Nutzung im Alltag. Die Montage wird auf das ausgewählte System und die örtlichen Bedingungen abgestimmt. Soll ein alter Zaun ersetzt werden, halten wir Rückbau und weitere Vorarbeiten im Angebot fest.

Die Kosten beim Zaunbau hängen von Länge und Höhe, Material, Toren, Untergrund und Zugänglichkeit ab. Ein einfacher gerader Verlauf verursacht einen anderen Aufwand als mehrere Ecken oder starke Höhenunterschiede. Für Ihre Anfrage sind Fotos, eine ungefähre Länge und Ihre Vorstellungen zu Sichtschutz und Zugang hilfreich. Wir klären daraus die nächsten Schritte und erstellen ein Angebot für die vereinbarte Anlage einschließlich der besprochenen Montagearbeiten.',
  meta_title='Zaunbau & Sichtschutz deutschlandweit | Loni GalaBau',
  meta_description='Zaunbau deutschlandweit: Zäune, Gartentore und Sichtschutz montieren lassen. Material, Verlauf und Untergrund mit Loni GalaBau persönlich abstimmen.',
  geo_focus='Deutschlandweit' where slug='zaunarbeiten' and short_text is not distinct from 'Zaunbau, Gartentore und Sichtschutz für Ihr Grundstück. Wir stimmen Material, Höhe, Verlauf und Montage auf Ihre Wünsche und die Gegebenheiten vor Ort ab.' and long_text is not distinct from 'Ein Gartenzaun markiert Grenzen, ein Tor ordnet den Zugang und ein Sichtschutz schafft einen geschützteren Sitzplatz. Loni GalaBau übernimmt Zaunarbeiten und Zaunbau in Hattersheim und im Rhein-Main-Gebiet. Gemeinsam klären wir, welche Aufgabe Ihre Anlage erfüllen soll: eine offene Einfriedung, mehr Privatsphäre oder eine Kombination mit einem passenden Gartentor.

Holz, Metall, Doppelstabmatten oder Gabionen wirken unterschiedlich und stellen unterschiedliche Anforderungen an Aufbau und Pflege. Wir besprechen Material, Farbe und Höhe im Zusammenhang mit Haus, Garten und angrenzenden Flächen. Auch der Verlauf ist wichtig: Ein Grundstück mit Gefälle benötigt andere Übergänge als eine ebene Fläche. Bestehende Mauern, Bäume und Wege werden bei der Planung berücksichtigt.

Bevor Sie einen Zaun montieren lassen, sollten Grundstücksgrenzen und erforderliche Abstimmungen geklärt sein. Wir sehen uns die vorgesehenen Standorte der Pfosten und den Untergrund an. Bei Toren besprechen wir Durchgangsbreite, Öffnungsrichtung und die Nutzung im Alltag. Die Montage wird auf das ausgewählte System und die örtlichen Bedingungen abgestimmt. Soll ein alter Zaun ersetzt werden, halten wir Rückbau und weitere Vorarbeiten im Angebot fest.

Die Kosten beim Zaunbau hängen von Länge und Höhe, Material, Toren, Untergrund und Zugänglichkeit ab. Ein einfacher gerader Verlauf verursacht einen anderen Aufwand als mehrere Ecken oder starke Höhenunterschiede. Für Ihre Anfrage sind Fotos, eine ungefähre Länge und Ihre Vorstellungen zu Sichtschutz und Zugang hilfreich. Wir klären daraus die nächsten Schritte und erstellen ein Angebot für die vereinbarte Anlage einschließlich der besprochenen Montagearbeiten.' and meta_title is not distinct from 'Zaunbau & Sichtschutz in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Zaunbau in Hattersheim und Rhein-Main: Zäune, Gartentore und Sichtschutz montieren lassen. Material, Verlauf und Untergrund gemeinsam abstimmen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: zaunarbeiten'; END IF;
update public.services set short_text='Rollrasen verlegen lassen oder Rasen neu einsäen: Wir bereiten die Fläche vor und stimmen Anlage, Bewässerung und erste Pflege mit Ihnen ab.',
  long_text='Eine neue Rasenfläche soll zum Garten und zu ihrer späteren Nutzung passen. Loni GalaBau legt Rasenanlagen in ganz Deutschland an. Sie können Rollrasen verlegen lassen oder sich für eine Einsaat entscheiden. Welche Variante zu Ihrem Vorhaben passt, besprechen wir anhand der Fläche, des gewünschten Zeitrahmens und der Möglichkeiten zur anschließenden Pflege.

Vor dem Grün kommt die Bodenvorbereitung. Wir betrachten den Zustand der vorhandenen Fläche, Höhen und Übergänge zu Wegen, Terrassen und Beeten. Je nach Bestand sind alte Rasensoden zu entfernen, Boden aufzubereiten oder Flächen neu zu modellieren. Welche Vorarbeiten erforderlich sind, wird im Leistungsumfang festgehalten. Auch Stellen, an denen sich Wasser sammelt, sollten vor der Neuanlage betrachtet werden.

Rollrasen bringt bereits eine geschlossene Grasnarbe mit; eine Einsaat entwickelt sich erst auf der vorbereiteten Fläche. Für beide Varianten sind die Bedingungen vor Ort und die Betreuung nach der Anlage wichtig. Wir stimmen die Ausführung mit Ihnen ab und besprechen Bewässerung, erste Pflege und Nutzung. Falls eine automatische Gartenbewässerung vorgesehen ist, lohnt es sich, die Leitungsplanung vor dem Anlegen des Rasens einzubeziehen.

Die Kosten für das Verlegen von Rollrasen oder eine Einsaat hängen nicht allein von der Fläche ab. Rückbau, Bodenarbeiten, Material, Zufahrt und mögliche Entsorgung beeinflussen den Aufwand. Senden Sie uns Fotos und ungefähre Maße und beschreiben Sie, ob es sich um eine bestehende Rasenfläche oder eine Neuanlage handelt. Daraus klären wir die notwendigen Schritte und erstellen ein Angebot mit dem vereinbarten Umfang.',
  meta_title='Rollrasen verlegen deutschlandweit | Loni GalaBau',
  meta_description='Rollrasen verlegen lassen oder Rasen einsäen – deutschlandweit. Bodenvorbereitung, Anlage und erste Pflege mit Loni GalaBau gemeinsam abstimmen.',
  geo_focus='Deutschlandweit' where slug='rasenanlagen' and short_text is not distinct from 'Rollrasen verlegen lassen oder Rasen neu einsäen: Wir bereiten die Fläche vor und stimmen Anlage, Bewässerung und erste Pflege mit Ihnen ab.' and long_text is not distinct from 'Eine neue Rasenfläche soll zum Garten und zu ihrer späteren Nutzung passen. Loni GalaBau legt Rasenanlagen in Hattersheim und im Rhein-Main-Gebiet an. Sie können Rollrasen verlegen lassen oder sich für eine Einsaat entscheiden. Welche Variante zu Ihrem Vorhaben passt, besprechen wir anhand der Fläche, des gewünschten Zeitrahmens und der Möglichkeiten zur anschließenden Pflege.

Vor dem Grün kommt die Bodenvorbereitung. Wir betrachten den Zustand der vorhandenen Fläche, Höhen und Übergänge zu Wegen, Terrassen und Beeten. Je nach Bestand sind alte Rasensoden zu entfernen, Boden aufzubereiten oder Flächen neu zu modellieren. Welche Vorarbeiten erforderlich sind, wird im Leistungsumfang festgehalten. Auch Stellen, an denen sich Wasser sammelt, sollten vor der Neuanlage betrachtet werden.

Rollrasen bringt bereits eine geschlossene Grasnarbe mit; eine Einsaat entwickelt sich erst auf der vorbereiteten Fläche. Für beide Varianten sind die Bedingungen vor Ort und die Betreuung nach der Anlage wichtig. Wir stimmen die Ausführung mit Ihnen ab und besprechen Bewässerung, erste Pflege und Nutzung. Falls eine automatische Gartenbewässerung vorgesehen ist, lohnt es sich, die Leitungsplanung vor dem Anlegen des Rasens einzubeziehen.

Die Kosten für das Verlegen von Rollrasen oder eine Einsaat hängen nicht allein von der Fläche ab. Rückbau, Bodenarbeiten, Material, Zufahrt und mögliche Entsorgung beeinflussen den Aufwand. Senden Sie uns Fotos und ungefähre Maße und beschreiben Sie, ob es sich um eine bestehende Rasenfläche oder eine Neuanlage handelt. Daraus klären wir die notwendigen Schritte und erstellen ein Angebot mit dem vereinbarten Umfang.' and meta_title is not distinct from 'Rollrasen verlegen in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Rollrasen verlegen lassen oder Rasen einsäen in Hattersheim und Rhein-Main. Bodenvorbereitung, Anlage und erste Pflege gemeinsam abstimmen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: rasenanlagen'; END IF;
update public.services set short_text='Erdarbeiten und Baggerarbeiten für Garten und Außenanlage: Aushub, Geländeanpassung und Bodenvorbereitung als Grundlage für die nächsten Bauarbeiten.',
  long_text='Bevor eine Terrasse, ein Gartenweg oder eine neue Rasenfläche entsteht, muss der Untergrund dazu passen. Loni GalaBau übernimmt Erdarbeiten im Garten und an Außenanlagen in ganz Deutschland. Wir heben Boden aus, passen Geländehöhen an und bereiten die vereinbarten Flächen für die folgenden Arbeiten vor. Den Umfang richten wir nach Ihrem Vorhaben und dem vorhandenen Grundstück aus.

Wenn Sie Ihren Garten begradigen lassen möchten, klären wir zuerst die geplanten Höhen und welche Anschlüsse erhalten bleiben. Haus, Wege, Nachbarflächen und die geplante Entwässerung gehören dabei zusammen betrachtet. Bei einem bestehenden Garten berücksichtigen wir außerdem Pflanzen und Bauteile, die erhalten werden sollen. Vorhandene Informationen zu Leitungen und Einbauten helfen, die Arbeiten vorzubereiten und offene Fragen vor Beginn zu klären.

Für Baggerarbeiten setzen wir unseren Fuhrpark passend zur Aufgabe ein. Wie die Baustelle erreichbar ist, beeinflusst den Ablauf wesentlich: Torbreite, Durchfahrt, Tragfähigkeit der Zufahrt und Platz für Material oder Fahrzeuge spielen eine Rolle. Deshalb besprechen wir die Zugänglichkeit frühzeitig. Ob Boden auf dem Grundstück weiterverwendet werden kann oder abgefahren werden muss, hängt von seiner Beschaffenheit und der Planung ab.

Die Kosten der Erdarbeiten ergeben sich aus Umfang, Bodenverhältnissen, Maschinenzugang, Transport und vereinbarter Entsorgung. Ein Flächenmaß allein reicht dafür häufig nicht aus. Für Ihre Anfrage helfen Fotos, ungefähre Maße, Angaben zu Höhenunterschieden und ein kurzer Hinweis auf das geplante Ergebnis. Wir stimmen die notwendigen Vorarbeiten mit Ihnen ab und halten fest, welche Leistungen im Angebot enthalten sind und wie sie mit Pflasterarbeiten, Entwässerung oder Gartengestaltung zusammenhängen.',
  meta_title='Erdarbeiten & Baggerarbeiten deutschlandweit | Loni GalaBau',
  meta_description='Erdarbeiten deutschlandweit: Aushub, Geländeanpassung und Bodenvorbereitung für Garten und Außenanlage. Ihr Vorhaben mit Loni GalaBau abstimmen.',
  geo_focus='Deutschlandweit' where slug='erdarbeiten' and short_text is not distinct from 'Erdarbeiten und Baggerarbeiten für Garten und Außenanlage: Aushub, Geländeanpassung und Bodenvorbereitung als Grundlage für die nächsten Bauarbeiten.' and long_text is not distinct from 'Bevor eine Terrasse, ein Gartenweg oder eine neue Rasenfläche entsteht, muss der Untergrund dazu passen. Loni GalaBau übernimmt Erdarbeiten im Garten und an Außenanlagen in Hattersheim und im Rhein-Main-Gebiet. Wir heben Boden aus, passen Geländehöhen an und bereiten die vereinbarten Flächen für die folgenden Arbeiten vor. Den Umfang richten wir nach Ihrem Vorhaben und dem vorhandenen Grundstück aus.

Wenn Sie Ihren Garten begradigen lassen möchten, klären wir zuerst die geplanten Höhen und welche Anschlüsse erhalten bleiben. Haus, Wege, Nachbarflächen und die geplante Entwässerung gehören dabei zusammen betrachtet. Bei einem bestehenden Garten berücksichtigen wir außerdem Pflanzen und Bauteile, die erhalten werden sollen. Vorhandene Informationen zu Leitungen und Einbauten helfen, die Arbeiten vorzubereiten und offene Fragen vor Beginn zu klären.

Für Baggerarbeiten setzen wir unseren Fuhrpark passend zur Aufgabe ein. Wie die Baustelle erreichbar ist, beeinflusst den Ablauf wesentlich: Torbreite, Durchfahrt, Tragfähigkeit der Zufahrt und Platz für Material oder Fahrzeuge spielen eine Rolle. Deshalb besprechen wir die Zugänglichkeit frühzeitig. Ob Boden auf dem Grundstück weiterverwendet werden kann oder abgefahren werden muss, hängt von seiner Beschaffenheit und der Planung ab.

Die Kosten der Erdarbeiten ergeben sich aus Umfang, Bodenverhältnissen, Maschinenzugang, Transport und vereinbarter Entsorgung. Ein Flächenmaß allein reicht dafür häufig nicht aus. Für Ihre Anfrage helfen Fotos, ungefähre Maße, Angaben zu Höhenunterschieden und ein kurzer Hinweis auf das geplante Ergebnis. Wir stimmen die notwendigen Vorarbeiten mit Ihnen ab und halten fest, welche Leistungen im Angebot enthalten sind und wie sie mit Pflasterarbeiten, Entwässerung oder Gartengestaltung zusammenhängen.' and meta_title is not distinct from 'Erdarbeiten & Baggerarbeiten Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Erdarbeiten in Hattersheim und Rhein-Main: Aushub, Geländeanpassung und Bodenvorbereitung für Garten und Außenanlage. Vorhaben persönlich abstimmen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: erdarbeiten'; END IF;
update public.services set short_text='Entwässerung für Garten, Einfahrt und Terrasse: Wir betrachten Gefälle, Rinnen, Abläufe und mögliche Versickerung im Zusammenhang mit Ihrem Grundstück.',
  long_text='Wenn Regenwasser auf der Einfahrt stehen bleibt oder sich an der Terrasse sammelt, lohnt sich ein Blick auf die gesamte Wasserführung. Loni GalaBau plant und baut Entwässerungslösungen für Außenanlagen in ganz Deutschland. Wir betrachten, wo Wasser anfällt, wie die Flächen geneigt sind und wohin es geführt werden kann. Die passende Lösung ergibt sich aus der Situation vor Ort.

Für befestigte Flächen können Entwässerungsrinnen und Abläufe Teil des Aufbaus sein. Im Garten kommen je nach Boden und Ausgangslage auch Drainagen oder Versickerungslösungen infrage. Eine einzelne Rinne oder ein Rohr löst das Problem jedoch nicht automatisch: Höhen, Gefälle, Aufnahme des Wassers und ein geeigneter weiterer Weg müssen zusammenpassen. Deshalb stimmen wir die Entwässerung mit vorhandenen oder geplanten Pflaster- und Gartenflächen ab.

Bevor wir eine Drainage verlegen oder eine Versickerung vorsehen, müssen Bodenverhältnisse, Anschlussmöglichkeiten und örtliche Vorgaben geklärt sein. Vorhandene Pläne und Informationen zur bisherigen Entwässerung sind dafür hilfreich. Bei einer Umgestaltung prüfen wir, welche Elemente erhalten bleiben können und welche Übergänge angepasst werden müssen. Den konkreten Aufbau und die erforderlichen Arbeiten besprechen wir für Ihr Grundstück.

Die Kosten hängen unter anderem von Fläche, Leitungswegen, Einbautiefe, Erdarbeiten und Wiederherstellung vorhandener Beläge ab. Für eine erste Anfrage helfen Fotos der betroffenen Bereiche, eine Skizze und Ihre Beobachtungen bei Regen. Beschreiben Sie auch, ob das Problem neu aufgetreten ist oder schon länger besteht. Nach Klärung der Ausgangslage erhalten Sie ein Angebot für die abgestimmten Maßnahmen und Hinweise zur späteren Kontrolle und Pflege.',
  meta_title='Entwässerung für Außenanlagen deutschlandweit | Loni GalaBau',
  meta_description='Entwässerung für Garten, Einfahrt und Terrasse – deutschlandweit. Gefälle, Rinnen und mögliche Drainage mit Loni GalaBau auf Ihr Grundstück abstimmen.',
  geo_focus='Deutschlandweit' where slug='entwaesserung' and short_text is not distinct from 'Entwässerung für Garten, Einfahrt und Terrasse: Wir betrachten Gefälle, Rinnen, Abläufe und mögliche Versickerung im Zusammenhang mit Ihrem Grundstück.' and long_text is not distinct from 'Wenn Regenwasser auf der Einfahrt stehen bleibt oder sich an der Terrasse sammelt, lohnt sich ein Blick auf die gesamte Wasserführung. Loni GalaBau plant und baut Entwässerungslösungen für Außenanlagen in Hattersheim und im Rhein-Main-Gebiet. Wir betrachten, wo Wasser anfällt, wie die Flächen geneigt sind und wohin es geführt werden kann. Die passende Lösung ergibt sich aus der Situation vor Ort.

Für befestigte Flächen können Entwässerungsrinnen und Abläufe Teil des Aufbaus sein. Im Garten kommen je nach Boden und Ausgangslage auch Drainagen oder Versickerungslösungen infrage. Eine einzelne Rinne oder ein Rohr löst das Problem jedoch nicht automatisch: Höhen, Gefälle, Aufnahme des Wassers und ein geeigneter weiterer Weg müssen zusammenpassen. Deshalb stimmen wir die Entwässerung mit vorhandenen oder geplanten Pflaster- und Gartenflächen ab.

Bevor wir eine Drainage verlegen oder eine Versickerung vorsehen, müssen Bodenverhältnisse, Anschlussmöglichkeiten und örtliche Vorgaben geklärt sein. Vorhandene Pläne und Informationen zur bisherigen Entwässerung sind dafür hilfreich. Bei einer Umgestaltung prüfen wir, welche Elemente erhalten bleiben können und welche Übergänge angepasst werden müssen. Den konkreten Aufbau und die erforderlichen Arbeiten besprechen wir für Ihr Grundstück.

Die Kosten hängen unter anderem von Fläche, Leitungswegen, Einbautiefe, Erdarbeiten und Wiederherstellung vorhandener Beläge ab. Für eine erste Anfrage helfen Fotos der betroffenen Bereiche, eine Skizze und Ihre Beobachtungen bei Regen. Beschreiben Sie auch, ob das Problem neu aufgetreten ist oder schon länger besteht. Nach Klärung der Ausgangslage erhalten Sie ein Angebot für die abgestimmten Maßnahmen und Hinweise zur späteren Kontrolle und Pflege.' and meta_title is not distinct from 'Entwässerung in Hattersheim | Loni GalaBau' and meta_description is not distinct from 'Entwässerung für Garten, Einfahrt und Terrasse in Hattersheim und Rhein-Main. Gefälle, Rinnen und mögliche Drainage auf Ihr Grundstück abstimmen.' and geo_focus is not distinct from 'Hattersheim & Rhein-Main';
GET DIAGNOSTICS affected = ROW_COUNT;
IF affected <> 1 THEN RAISE EXCEPTION 'Content changed concurrently: entwaesserung'; END IF;
END $nationwide$;
