/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ProjekteRouteImport } from './routes/projekte'
import { Route as PartnerWerdenRouteImport } from './routes/partner-werden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KonfiguratorRouteImport } from './routes/konfigurator'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GartenbauSulzbachTaunusRouteImport } from './routes/gartenbau-sulzbach-taunus'
import { Route as GartenbauKriftelRouteImport } from './routes/gartenbau-kriftel'
import { Route as GartenbauKelsterbachRouteImport } from './routes/gartenbau-kelsterbach'
import { Route as GartenbauHofheimRouteImport } from './routes/gartenbau-hofheim'
import { Route as GartenbauHochheimRouteImport } from './routes/gartenbau-hochheim'
import { Route as GartenbauHattersheimRouteImport } from './routes/gartenbau-hattersheim'
import { Route as GartenbauFrankfurtHoechstRouteImport } from './routes/gartenbau-frankfurt-hoechst'
import { Route as GartenbauFloersheimRouteImport } from './routes/gartenbau-floersheim'
import { Route as GartenbauEschbornRouteImport } from './routes/gartenbau-eschborn'
import { Route as GartenbauBadSodenRouteImport } from './routes/gartenbau-bad-soden'
import { Route as EinsatzgebieteRouteImport } from './routes/einsatzgebiete'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber.index'
import { Route as OpenseoIndexRouteImport } from './routes/openseo.index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as RatgeberSlugRouteImport } from './routes/ratgeber.$slug'
import { Route as ProjekteIdRouteImport } from './routes/projekte_.$id'
import { Route as OpenseoNutzungRouteImport } from './routes/openseo.nutzung'
import { Route as OpenseoDatenschutzRouteImport } from './routes/openseo.datenschutz'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as AutorenSerhadMarasliRouteImport } from './routes/autoren.serhad-marasli'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminWissensbankRouteImport } from './routes/_authenticated/admin/wissensbank'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/admin/tracking'
import { Route as AuthenticatedAdminProjekteRouteImport } from './routes/_authenticated/admin/projekte'
import { Route as AuthenticatedAdminPartnerRouteImport } from './routes/_authenticated/admin/partner'
import { Route as AuthenticatedAdminLeistungenRouteImport } from './routes/_authenticated/admin/leistungen'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminBilderRouteImport } from './routes/_authenticated/admin/bilder'
import { Route as AuthenticatedAdminBewerbungenRouteImport } from './routes/_authenticated/admin/bewerbungen'
import { Route as AuthenticatedAdminAssistentRouteImport } from './routes/_authenticated/admin/assistent'
import { Route as AuthenticatedAdminAnfragenRouteImport } from './routes/_authenticated/admin/anfragen'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteRoute = ProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWerdenRoute = PartnerWerdenRouteImport.update({
  id: '/partner-werden',
  path: '/partner-werden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfiguratorRoute = KonfiguratorRouteImport.update({
  id: '/konfigurator',
  path: '/konfigurator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauSulzbachTaunusRoute = GartenbauSulzbachTaunusRouteImport.update({
  id: '/gartenbau-sulzbach-taunus',
  path: '/gartenbau-sulzbach-taunus',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauKriftelRoute = GartenbauKriftelRouteImport.update({
  id: '/gartenbau-kriftel',
  path: '/gartenbau-kriftel',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauKelsterbachRoute = GartenbauKelsterbachRouteImport.update({
  id: '/gartenbau-kelsterbach',
  path: '/gartenbau-kelsterbach',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauHofheimRoute = GartenbauHofheimRouteImport.update({
  id: '/gartenbau-hofheim',
  path: '/gartenbau-hofheim',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauHochheimRoute = GartenbauHochheimRouteImport.update({
  id: '/gartenbau-hochheim',
  path: '/gartenbau-hochheim',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauHattersheimRoute = GartenbauHattersheimRouteImport.update({
  id: '/gartenbau-hattersheim',
  path: '/gartenbau-hattersheim',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauFrankfurtHoechstRoute =
  GartenbauFrankfurtHoechstRouteImport.update({
    id: '/gartenbau-frankfurt-hoechst',
    path: '/gartenbau-frankfurt-hoechst',
    getParentRoute: () => rootRouteImport,
  } as any)
const GartenbauFloersheimRoute = GartenbauFloersheimRouteImport.update({
  id: '/gartenbau-floersheim',
  path: '/gartenbau-floersheim',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauEschbornRoute = GartenbauEschbornRouteImport.update({
  id: '/gartenbau-eschborn',
  path: '/gartenbau-eschborn',
  getParentRoute: () => rootRouteImport,
} as any)
const GartenbauBadSodenRoute = GartenbauBadSodenRouteImport.update({
  id: '/gartenbau-bad-soden',
  path: '/gartenbau-bad-soden',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsatzgebieteRoute = EinsatzgebieteRouteImport.update({
  id: '/einsatzgebiete',
  path: '/einsatzgebiete',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoIndexRoute = OpenseoIndexRouteImport.update({
  id: '/openseo/',
  path: '/openseo/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberSlugRoute = RatgeberSlugRouteImport.update({
  id: '/ratgeber/$slug',
  path: '/ratgeber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteIdRoute = ProjekteIdRouteImport.update({
  id: '/projekte_/$id',
  path: '/projekte/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoNutzungRoute = OpenseoNutzungRouteImport.update({
  id: '/openseo/nutzung',
  path: '/openseo/nutzung',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoDatenschutzRoute = OpenseoDatenschutzRouteImport.update({
  id: '/openseo/datenschutz',
  path: '/openseo/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/leistungen/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorenSerhadMarasliRoute = AutorenSerhadMarasliRouteImport.update({
  id: '/autoren/serhad-marasli',
  path: '/autoren/serhad-marasli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWissensbankRoute =
  AuthenticatedAdminWissensbankRouteImport.update({
    id: '/admin/wissensbank',
    path: '/admin/wissensbank',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/admin/tracking',
    path: '/admin/tracking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjekteRoute =
  AuthenticatedAdminProjekteRouteImport.update({
    id: '/admin/projekte',
    path: '/admin/projekte',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPartnerRoute =
  AuthenticatedAdminPartnerRouteImport.update({
    id: '/admin/partner',
    path: '/admin/partner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeistungenRoute =
  AuthenticatedAdminLeistungenRouteImport.update({
    id: '/admin/leistungen',
    path: '/admin/leistungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminBilderRoute =
  AuthenticatedAdminBilderRouteImport.update({
    id: '/admin/bilder',
    path: '/admin/bilder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBewerbungenRoute =
  AuthenticatedAdminBewerbungenRouteImport.update({
    id: '/admin/bewerbungen',
    path: '/admin/bewerbungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAssistentRoute =
  AuthenticatedAdminAssistentRouteImport.update({
    id: '/admin/assistent',
    path: '/admin/assistent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnfragenRoute =
  AuthenticatedAdminAnfragenRouteImport.update({
    id: '/admin/anfragen',
    path: '/admin/anfragen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/einsatzgebiete': typeof EinsatzgebieteRoute
  '/gartenbau-bad-soden': typeof GartenbauBadSodenRoute
  '/gartenbau-eschborn': typeof GartenbauEschbornRoute
  '/gartenbau-floersheim': typeof GartenbauFloersheimRoute
  '/gartenbau-frankfurt-hoechst': typeof GartenbauFrankfurtHoechstRoute
  '/gartenbau-hattersheim': typeof GartenbauHattersheimRoute
  '/gartenbau-hochheim': typeof GartenbauHochheimRoute
  '/gartenbau-hofheim': typeof GartenbauHofheimRoute
  '/gartenbau-kelsterbach': typeof GartenbauKelsterbachRoute
  '/gartenbau-kriftel': typeof GartenbauKriftelRoute
  '/gartenbau-sulzbach-taunus': typeof GartenbauSulzbachTaunusRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/partner-werden': typeof PartnerWerdenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/openseo/': typeof OpenseoIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/admin/assistent': typeof AuthenticatedAdminAssistentRoute
  '/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/admin/partner': typeof AuthenticatedAdminPartnerRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin/wissensbank': typeof AuthenticatedAdminWissensbankRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/einsatzgebiete': typeof EinsatzgebieteRoute
  '/gartenbau-bad-soden': typeof GartenbauBadSodenRoute
  '/gartenbau-eschborn': typeof GartenbauEschbornRoute
  '/gartenbau-floersheim': typeof GartenbauFloersheimRoute
  '/gartenbau-frankfurt-hoechst': typeof GartenbauFrankfurtHoechstRoute
  '/gartenbau-hattersheim': typeof GartenbauHattersheimRoute
  '/gartenbau-hochheim': typeof GartenbauHochheimRoute
  '/gartenbau-hofheim': typeof GartenbauHofheimRoute
  '/gartenbau-kelsterbach': typeof GartenbauKelsterbachRoute
  '/gartenbau-kriftel': typeof GartenbauKriftelRoute
  '/gartenbau-sulzbach-taunus': typeof GartenbauSulzbachTaunusRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/partner-werden': typeof PartnerWerdenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs': typeof JobsIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/openseo': typeof OpenseoIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/admin/assistent': typeof AuthenticatedAdminAssistentRoute
  '/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/admin/partner': typeof AuthenticatedAdminPartnerRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin/wissensbank': typeof AuthenticatedAdminWissensbankRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/einsatzgebiete': typeof EinsatzgebieteRoute
  '/gartenbau-bad-soden': typeof GartenbauBadSodenRoute
  '/gartenbau-eschborn': typeof GartenbauEschbornRoute
  '/gartenbau-floersheim': typeof GartenbauFloersheimRoute
  '/gartenbau-frankfurt-hoechst': typeof GartenbauFrankfurtHoechstRoute
  '/gartenbau-hattersheim': typeof GartenbauHattersheimRoute
  '/gartenbau-hochheim': typeof GartenbauHochheimRoute
  '/gartenbau-hofheim': typeof GartenbauHofheimRoute
  '/gartenbau-kelsterbach': typeof GartenbauKelsterbachRoute
  '/gartenbau-kriftel': typeof GartenbauKriftelRoute
  '/gartenbau-sulzbach-taunus': typeof GartenbauSulzbachTaunusRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/partner-werden': typeof PartnerWerdenRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte_/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/openseo/': typeof OpenseoIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/_authenticated/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/_authenticated/admin/assistent': typeof AuthenticatedAdminAssistentRoute
  '/_authenticated/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/_authenticated/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/_authenticated/admin/partner': typeof AuthenticatedAdminPartnerRoute
  '/_authenticated/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/admin/wissensbank': typeof AuthenticatedAdminWissensbankRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/einsatzgebiete'
    | '/gartenbau-bad-soden'
    | '/gartenbau-eschborn'
    | '/gartenbau-floersheim'
    | '/gartenbau-frankfurt-hoechst'
    | '/gartenbau-hattersheim'
    | '/gartenbau-hochheim'
    | '/gartenbau-hofheim'
    | '/gartenbau-kelsterbach'
    | '/gartenbau-kriftel'
    | '/gartenbau-sulzbach-taunus'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/partner-werden'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte/$id'
    | '/ratgeber/$slug'
    | '/jobs/'
    | '/leistungen/'
    | '/openseo/'
    | '/ratgeber/'
    | '/admin/anfragen'
    | '/admin/assistent'
    | '/admin/bewerbungen'
    | '/admin/bilder'
    | '/admin/jobs'
    | '/admin/leistungen'
    | '/admin/partner'
    | '/admin/projekte'
    | '/admin/tracking'
    | '/admin/wissensbank'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/einsatzgebiete'
    | '/gartenbau-bad-soden'
    | '/gartenbau-eschborn'
    | '/gartenbau-floersheim'
    | '/gartenbau-frankfurt-hoechst'
    | '/gartenbau-hattersheim'
    | '/gartenbau-hochheim'
    | '/gartenbau-hofheim'
    | '/gartenbau-kelsterbach'
    | '/gartenbau-kriftel'
    | '/gartenbau-sulzbach-taunus'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/partner-werden'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte/$id'
    | '/ratgeber/$slug'
    | '/jobs'
    | '/leistungen'
    | '/openseo'
    | '/ratgeber'
    | '/admin/anfragen'
    | '/admin/assistent'
    | '/admin/bewerbungen'
    | '/admin/bilder'
    | '/admin/jobs'
    | '/admin/leistungen'
    | '/admin/partner'
    | '/admin/projekte'
    | '/admin/tracking'
    | '/admin/wissensbank'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/einsatzgebiete'
    | '/gartenbau-bad-soden'
    | '/gartenbau-eschborn'
    | '/gartenbau-floersheim'
    | '/gartenbau-frankfurt-hoechst'
    | '/gartenbau-hattersheim'
    | '/gartenbau-hochheim'
    | '/gartenbau-hofheim'
    | '/gartenbau-kelsterbach'
    | '/gartenbau-kriftel'
    | '/gartenbau-sulzbach-taunus'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/partner-werden'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte_/$id'
    | '/ratgeber/$slug'
    | '/jobs/'
    | '/leistungen/'
    | '/openseo/'
    | '/ratgeber/'
    | '/_authenticated/admin/anfragen'
    | '/_authenticated/admin/assistent'
    | '/_authenticated/admin/bewerbungen'
    | '/_authenticated/admin/bilder'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/leistungen'
    | '/_authenticated/admin/partner'
    | '/_authenticated/admin/projekte'
    | '/_authenticated/admin/tracking'
    | '/_authenticated/admin/wissensbank'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DownloadsRoute: typeof DownloadsRoute
  EinsatzgebieteRoute: typeof EinsatzgebieteRoute
  GartenbauBadSodenRoute: typeof GartenbauBadSodenRoute
  GartenbauEschbornRoute: typeof GartenbauEschbornRoute
  GartenbauFloersheimRoute: typeof GartenbauFloersheimRoute
  GartenbauFrankfurtHoechstRoute: typeof GartenbauFrankfurtHoechstRoute
  GartenbauHattersheimRoute: typeof GartenbauHattersheimRoute
  GartenbauHochheimRoute: typeof GartenbauHochheimRoute
  GartenbauHofheimRoute: typeof GartenbauHofheimRoute
  GartenbauKelsterbachRoute: typeof GartenbauKelsterbachRoute
  GartenbauKriftelRoute: typeof GartenbauKriftelRoute
  GartenbauSulzbachTaunusRoute: typeof GartenbauSulzbachTaunusRoute
  ImpressumRoute: typeof ImpressumRoute
  KonfiguratorRoute: typeof KonfiguratorRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  PartnerWerdenRoute: typeof PartnerWerdenRoute
  ProjekteRoute: typeof ProjekteRoute
  UeberUnsRoute: typeof UeberUnsRoute
  AutorenSerhadMarasliRoute: typeof AutorenSerhadMarasliRoute
  JobsSlugRoute: typeof JobsSlugRoute
  LeistungenSlugRoute: typeof LeistungenSlugRoute
  OpenseoDatenschutzRoute: typeof OpenseoDatenschutzRoute
  OpenseoNutzungRoute: typeof OpenseoNutzungRoute
  ProjekteIdRoute: typeof ProjekteIdRoute
  RatgeberSlugRoute: typeof RatgeberSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
  OpenseoIndexRoute: typeof OpenseoIndexRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte': {
      id: '/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof ProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-werden': {
      id: '/partner-werden'
      path: '/partner-werden'
      fullPath: '/partner-werden'
      preLoaderRoute: typeof PartnerWerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfigurator': {
      id: '/konfigurator'
      path: '/konfigurator'
      fullPath: '/konfigurator'
      preLoaderRoute: typeof KonfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-sulzbach-taunus': {
      id: '/gartenbau-sulzbach-taunus'
      path: '/gartenbau-sulzbach-taunus'
      fullPath: '/gartenbau-sulzbach-taunus'
      preLoaderRoute: typeof GartenbauSulzbachTaunusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-kriftel': {
      id: '/gartenbau-kriftel'
      path: '/gartenbau-kriftel'
      fullPath: '/gartenbau-kriftel'
      preLoaderRoute: typeof GartenbauKriftelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-kelsterbach': {
      id: '/gartenbau-kelsterbach'
      path: '/gartenbau-kelsterbach'
      fullPath: '/gartenbau-kelsterbach'
      preLoaderRoute: typeof GartenbauKelsterbachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-hofheim': {
      id: '/gartenbau-hofheim'
      path: '/gartenbau-hofheim'
      fullPath: '/gartenbau-hofheim'
      preLoaderRoute: typeof GartenbauHofheimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-hochheim': {
      id: '/gartenbau-hochheim'
      path: '/gartenbau-hochheim'
      fullPath: '/gartenbau-hochheim'
      preLoaderRoute: typeof GartenbauHochheimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-hattersheim': {
      id: '/gartenbau-hattersheim'
      path: '/gartenbau-hattersheim'
      fullPath: '/gartenbau-hattersheim'
      preLoaderRoute: typeof GartenbauHattersheimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-frankfurt-hoechst': {
      id: '/gartenbau-frankfurt-hoechst'
      path: '/gartenbau-frankfurt-hoechst'
      fullPath: '/gartenbau-frankfurt-hoechst'
      preLoaderRoute: typeof GartenbauFrankfurtHoechstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-floersheim': {
      id: '/gartenbau-floersheim'
      path: '/gartenbau-floersheim'
      fullPath: '/gartenbau-floersheim'
      preLoaderRoute: typeof GartenbauFloersheimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-eschborn': {
      id: '/gartenbau-eschborn'
      path: '/gartenbau-eschborn'
      fullPath: '/gartenbau-eschborn'
      preLoaderRoute: typeof GartenbauEschbornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gartenbau-bad-soden': {
      id: '/gartenbau-bad-soden'
      path: '/gartenbau-bad-soden'
      fullPath: '/gartenbau-bad-soden'
      preLoaderRoute: typeof GartenbauBadSodenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsatzgebiete': {
      id: '/einsatzgebiete'
      path: '/einsatzgebiete'
      fullPath: '/einsatzgebiete'
      preLoaderRoute: typeof EinsatzgebieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/ratgeber'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/': {
      id: '/openseo/'
      path: '/openseo'
      fullPath: '/openseo/'
      preLoaderRoute: typeof OpenseoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/$slug': {
      id: '/ratgeber/$slug'
      path: '/ratgeber/$slug'
      fullPath: '/ratgeber/$slug'
      preLoaderRoute: typeof RatgeberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte_/$id': {
      id: '/projekte_/$id'
      path: '/projekte/$id'
      fullPath: '/projekte/$id'
      preLoaderRoute: typeof ProjekteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/nutzung': {
      id: '/openseo/nutzung'
      path: '/openseo/nutzung'
      fullPath: '/openseo/nutzung'
      preLoaderRoute: typeof OpenseoNutzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/datenschutz': {
      id: '/openseo/datenschutz'
      path: '/openseo/datenschutz'
      fullPath: '/openseo/datenschutz'
      preLoaderRoute: typeof OpenseoDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoren/serhad-marasli': {
      id: '/autoren/serhad-marasli'
      path: '/autoren/serhad-marasli'
      fullPath: '/autoren/serhad-marasli'
      preLoaderRoute: typeof AutorenSerhadMarasliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/wissensbank': {
      id: '/_authenticated/admin/wissensbank'
      path: '/admin/wissensbank'
      fullPath: '/admin/wissensbank'
      preLoaderRoute: typeof AuthenticatedAdminWissensbankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tracking': {
      id: '/_authenticated/admin/tracking'
      path: '/admin/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projekte': {
      id: '/_authenticated/admin/projekte'
      path: '/admin/projekte'
      fullPath: '/admin/projekte'
      preLoaderRoute: typeof AuthenticatedAdminProjekteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/partner': {
      id: '/_authenticated/admin/partner'
      path: '/admin/partner'
      fullPath: '/admin/partner'
      preLoaderRoute: typeof AuthenticatedAdminPartnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leistungen': {
      id: '/_authenticated/admin/leistungen'
      path: '/admin/leistungen'
      fullPath: '/admin/leistungen'
      preLoaderRoute: typeof AuthenticatedAdminLeistungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bilder': {
      id: '/_authenticated/admin/bilder'
      path: '/admin/bilder'
      fullPath: '/admin/bilder'
      preLoaderRoute: typeof AuthenticatedAdminBilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bewerbungen': {
      id: '/_authenticated/admin/bewerbungen'
      path: '/admin/bewerbungen'
      fullPath: '/admin/bewerbungen'
      preLoaderRoute: typeof AuthenticatedAdminBewerbungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/assistent': {
      id: '/_authenticated/admin/assistent'
      path: '/admin/assistent'
      fullPath: '/admin/assistent'
      preLoaderRoute: typeof AuthenticatedAdminAssistentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/anfragen': {
      id: '/_authenticated/admin/anfragen'
      path: '/admin/anfragen'
      fullPath: '/admin/anfragen'
      preLoaderRoute: typeof AuthenticatedAdminAnfragenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAnfragenRoute: typeof AuthenticatedAdminAnfragenRoute
  AuthenticatedAdminAssistentRoute: typeof AuthenticatedAdminAssistentRoute
  AuthenticatedAdminBewerbungenRoute: typeof AuthenticatedAdminBewerbungenRoute
  AuthenticatedAdminBilderRoute: typeof AuthenticatedAdminBilderRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminLeistungenRoute: typeof AuthenticatedAdminLeistungenRoute
  AuthenticatedAdminPartnerRoute: typeof AuthenticatedAdminPartnerRoute
  AuthenticatedAdminProjekteRoute: typeof AuthenticatedAdminProjekteRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminWissensbankRoute: typeof AuthenticatedAdminWissensbankRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAnfragenRoute: AuthenticatedAdminAnfragenRoute,
  AuthenticatedAdminAssistentRoute: AuthenticatedAdminAssistentRoute,
  AuthenticatedAdminBewerbungenRoute: AuthenticatedAdminBewerbungenRoute,
  AuthenticatedAdminBilderRoute: AuthenticatedAdminBilderRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminLeistungenRoute: AuthenticatedAdminLeistungenRoute,
  AuthenticatedAdminPartnerRoute: AuthenticatedAdminPartnerRoute,
  AuthenticatedAdminProjekteRoute: AuthenticatedAdminProjekteRoute,
  AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
  AuthenticatedAdminWissensbankRoute: AuthenticatedAdminWissensbankRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  DownloadsRoute: DownloadsRoute,
  EinsatzgebieteRoute: EinsatzgebieteRoute,
  GartenbauBadSodenRoute: GartenbauBadSodenRoute,
  GartenbauEschbornRoute: GartenbauEschbornRoute,
  GartenbauFloersheimRoute: GartenbauFloersheimRoute,
  GartenbauFrankfurtHoechstRoute: GartenbauFrankfurtHoechstRoute,
  GartenbauHattersheimRoute: GartenbauHattersheimRoute,
  GartenbauHochheimRoute: GartenbauHochheimRoute,
  GartenbauHofheimRoute: GartenbauHofheimRoute,
  GartenbauKelsterbachRoute: GartenbauKelsterbachRoute,
  GartenbauKriftelRoute: GartenbauKriftelRoute,
  GartenbauSulzbachTaunusRoute: GartenbauSulzbachTaunusRoute,
  ImpressumRoute: ImpressumRoute,
  KonfiguratorRoute: KonfiguratorRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  PartnerWerdenRoute: PartnerWerdenRoute,
  ProjekteRoute: ProjekteRoute,
  UeberUnsRoute: UeberUnsRoute,
  AutorenSerhadMarasliRoute: AutorenSerhadMarasliRoute,
  JobsSlugRoute: JobsSlugRoute,
  LeistungenSlugRoute: LeistungenSlugRoute,
  OpenseoDatenschutzRoute: OpenseoDatenschutzRoute,
  OpenseoNutzungRoute: OpenseoNutzungRoute,
  ProjekteIdRoute: ProjekteIdRoute,
  RatgeberSlugRoute: RatgeberSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
  OpenseoIndexRoute: OpenseoIndexRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
