/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ProjekteRouteImport } from './routes/projekte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KonfiguratorRouteImport } from './routes/konfigurator'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber.index'
import { Route as OpenseoIndexRouteImport } from './routes/openseo.index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as RatgeberSlugRouteImport } from './routes/ratgeber.$slug'
import { Route as ProjekteIdRouteImport } from './routes/projekte_.$id'
import { Route as OpenseoNutzungRouteImport } from './routes/openseo.nutzung'
import { Route as OpenseoDatenschutzRouteImport } from './routes/openseo.datenschutz'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as AutorenSerhadMarasliRouteImport } from './routes/autoren.serhad-marasli'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/admin/tracking'
import { Route as AuthenticatedAdminProjekteRouteImport } from './routes/_authenticated/admin/projekte'
import { Route as AuthenticatedAdminLeistungenRouteImport } from './routes/_authenticated/admin/leistungen'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminBilderRouteImport } from './routes/_authenticated/admin/bilder'
import { Route as AuthenticatedAdminBewerbungenRouteImport } from './routes/_authenticated/admin/bewerbungen'
import { Route as AuthenticatedAdminAnfragenRouteImport } from './routes/_authenticated/admin/anfragen'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteRoute = ProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfiguratorRoute = KonfiguratorRouteImport.update({
  id: '/konfigurator',
  path: '/konfigurator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoIndexRoute = OpenseoIndexRouteImport.update({
  id: '/openseo/',
  path: '/openseo/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberSlugRoute = RatgeberSlugRouteImport.update({
  id: '/ratgeber/$slug',
  path: '/ratgeber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteIdRoute = ProjekteIdRouteImport.update({
  id: '/projekte_/$id',
  path: '/projekte/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoNutzungRoute = OpenseoNutzungRouteImport.update({
  id: '/openseo/nutzung',
  path: '/openseo/nutzung',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenseoDatenschutzRoute = OpenseoDatenschutzRouteImport.update({
  id: '/openseo/datenschutz',
  path: '/openseo/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/leistungen/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorenSerhadMarasliRoute = AutorenSerhadMarasliRouteImport.update({
  id: '/autoren/serhad-marasli',
  path: '/autoren/serhad-marasli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/admin/tracking',
    path: '/admin/tracking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjekteRoute =
  AuthenticatedAdminProjekteRouteImport.update({
    id: '/admin/projekte',
    path: '/admin/projekte',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeistungenRoute =
  AuthenticatedAdminLeistungenRouteImport.update({
    id: '/admin/leistungen',
    path: '/admin/leistungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminBilderRoute =
  AuthenticatedAdminBilderRouteImport.update({
    id: '/admin/bilder',
    path: '/admin/bilder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBewerbungenRoute =
  AuthenticatedAdminBewerbungenRouteImport.update({
    id: '/admin/bewerbungen',
    path: '/admin/bewerbungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnfragenRoute =
  AuthenticatedAdminAnfragenRouteImport.update({
    id: '/admin/anfragen',
    path: '/admin/anfragen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/openseo/': typeof OpenseoIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs': typeof JobsIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/openseo': typeof OpenseoIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/downloads': typeof DownloadsRoute
  '/impressum': typeof ImpressumRoute
  '/konfigurator': typeof KonfiguratorRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/projekte': typeof ProjekteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/autoren/serhad-marasli': typeof AutorenSerhadMarasliRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/openseo/datenschutz': typeof OpenseoDatenschutzRoute
  '/openseo/nutzung': typeof OpenseoNutzungRoute
  '/projekte_/$id': typeof ProjekteIdRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/openseo/': typeof OpenseoIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/_authenticated/admin/anfragen': typeof AuthenticatedAdminAnfragenRoute
  '/_authenticated/admin/bewerbungen': typeof AuthenticatedAdminBewerbungenRoute
  '/_authenticated/admin/bilder': typeof AuthenticatedAdminBilderRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/leistungen': typeof AuthenticatedAdminLeistungenRoute
  '/_authenticated/admin/projekte': typeof AuthenticatedAdminProjekteRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte/$id'
    | '/ratgeber/$slug'
    | '/jobs/'
    | '/leistungen/'
    | '/openseo/'
    | '/ratgeber/'
    | '/admin/anfragen'
    | '/admin/bewerbungen'
    | '/admin/bilder'
    | '/admin/jobs'
    | '/admin/leistungen'
    | '/admin/projekte'
    | '/admin/tracking'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte/$id'
    | '/ratgeber/$slug'
    | '/jobs'
    | '/leistungen'
    | '/openseo'
    | '/ratgeber'
    | '/admin/anfragen'
    | '/admin/bewerbungen'
    | '/admin/bilder'
    | '/admin/jobs'
    | '/admin/leistungen'
    | '/admin/projekte'
    | '/admin/tracking'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/datenschutz'
    | '/downloads'
    | '/impressum'
    | '/konfigurator'
    | '/kontakt'
    | '/login'
    | '/projekte'
    | '/ueber-uns'
    | '/autoren/serhad-marasli'
    | '/jobs/$slug'
    | '/leistungen/$slug'
    | '/openseo/datenschutz'
    | '/openseo/nutzung'
    | '/projekte_/$id'
    | '/ratgeber/$slug'
    | '/jobs/'
    | '/leistungen/'
    | '/openseo/'
    | '/ratgeber/'
    | '/_authenticated/admin/anfragen'
    | '/_authenticated/admin/bewerbungen'
    | '/_authenticated/admin/bilder'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/leistungen'
    | '/_authenticated/admin/projekte'
    | '/_authenticated/admin/tracking'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DownloadsRoute: typeof DownloadsRoute
  ImpressumRoute: typeof ImpressumRoute
  KonfiguratorRoute: typeof KonfiguratorRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  ProjekteRoute: typeof ProjekteRoute
  UeberUnsRoute: typeof UeberUnsRoute
  AutorenSerhadMarasliRoute: typeof AutorenSerhadMarasliRoute
  JobsSlugRoute: typeof JobsSlugRoute
  LeistungenSlugRoute: typeof LeistungenSlugRoute
  OpenseoDatenschutzRoute: typeof OpenseoDatenschutzRoute
  OpenseoNutzungRoute: typeof OpenseoNutzungRoute
  ProjekteIdRoute: typeof ProjekteIdRoute
  RatgeberSlugRoute: typeof RatgeberSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
  OpenseoIndexRoute: typeof OpenseoIndexRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte': {
      id: '/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof ProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfigurator': {
      id: '/konfigurator'
      path: '/konfigurator'
      fullPath: '/konfigurator'
      preLoaderRoute: typeof KonfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/ratgeber'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/': {
      id: '/openseo/'
      path: '/openseo'
      fullPath: '/openseo/'
      preLoaderRoute: typeof OpenseoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/$slug': {
      id: '/ratgeber/$slug'
      path: '/ratgeber/$slug'
      fullPath: '/ratgeber/$slug'
      preLoaderRoute: typeof RatgeberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte_/$id': {
      id: '/projekte_/$id'
      path: '/projekte/$id'
      fullPath: '/projekte/$id'
      preLoaderRoute: typeof ProjekteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/nutzung': {
      id: '/openseo/nutzung'
      path: '/openseo/nutzung'
      fullPath: '/openseo/nutzung'
      preLoaderRoute: typeof OpenseoNutzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openseo/datenschutz': {
      id: '/openseo/datenschutz'
      path: '/openseo/datenschutz'
      fullPath: '/openseo/datenschutz'
      preLoaderRoute: typeof OpenseoDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoren/serhad-marasli': {
      id: '/autoren/serhad-marasli'
      path: '/autoren/serhad-marasli'
      fullPath: '/autoren/serhad-marasli'
      preLoaderRoute: typeof AutorenSerhadMarasliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tracking': {
      id: '/_authenticated/admin/tracking'
      path: '/admin/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projekte': {
      id: '/_authenticated/admin/projekte'
      path: '/admin/projekte'
      fullPath: '/admin/projekte'
      preLoaderRoute: typeof AuthenticatedAdminProjekteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leistungen': {
      id: '/_authenticated/admin/leistungen'
      path: '/admin/leistungen'
      fullPath: '/admin/leistungen'
      preLoaderRoute: typeof AuthenticatedAdminLeistungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bilder': {
      id: '/_authenticated/admin/bilder'
      path: '/admin/bilder'
      fullPath: '/admin/bilder'
      preLoaderRoute: typeof AuthenticatedAdminBilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bewerbungen': {
      id: '/_authenticated/admin/bewerbungen'
      path: '/admin/bewerbungen'
      fullPath: '/admin/bewerbungen'
      preLoaderRoute: typeof AuthenticatedAdminBewerbungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/anfragen': {
      id: '/_authenticated/admin/anfragen'
      path: '/admin/anfragen'
      fullPath: '/admin/anfragen'
      preLoaderRoute: typeof AuthenticatedAdminAnfragenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAnfragenRoute: typeof AuthenticatedAdminAnfragenRoute
  AuthenticatedAdminBewerbungenRoute: typeof AuthenticatedAdminBewerbungenRoute
  AuthenticatedAdminBilderRoute: typeof AuthenticatedAdminBilderRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminLeistungenRoute: typeof AuthenticatedAdminLeistungenRoute
  AuthenticatedAdminProjekteRoute: typeof AuthenticatedAdminProjekteRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAnfragenRoute: AuthenticatedAdminAnfragenRoute,
  AuthenticatedAdminBewerbungenRoute: AuthenticatedAdminBewerbungenRoute,
  AuthenticatedAdminBilderRoute: AuthenticatedAdminBilderRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminLeistungenRoute: AuthenticatedAdminLeistungenRoute,
  AuthenticatedAdminProjekteRoute: AuthenticatedAdminProjekteRoute,
  AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  DownloadsRoute: DownloadsRoute,
  ImpressumRoute: ImpressumRoute,
  KonfiguratorRoute: KonfiguratorRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  ProjekteRoute: ProjekteRoute,
  UeberUnsRoute: UeberUnsRoute,
  AutorenSerhadMarasliRoute: AutorenSerhadMarasliRoute,
  JobsSlugRoute: JobsSlugRoute,
  LeistungenSlugRoute: LeistungenSlugRoute,
  OpenseoDatenschutzRoute: OpenseoDatenschutzRoute,
  OpenseoNutzungRoute: OpenseoNutzungRoute,
  ProjekteIdRoute: ProjekteIdRoute,
  RatgeberSlugRoute: RatgeberSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
  OpenseoIndexRoute: OpenseoIndexRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
