-- Öffentliche Website-Inhalte aus dem bisherigen Projekt. Keine Kundendaten oder Konten.
-- Export: 2026-09-28T08:27:11.178Z
-- Erst nach 01_schema.sql und 02_storage.sql im neuen Projekt ausführen.
-- Bild-URLs werden zunächst unverändert übernommen; Quellprojekt bis zur Dateimigration behalten.
BEGIN;
SET LOCAL standard_conforming_strings = on;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM public.services) OR EXISTS (SELECT 1 FROM public.projects) OR EXISTS (SELECT 1 FROM public.jobs) THEN
    RAISE EXCEPTION 'Abbruch: Ziel enthält bereits Website-Inhalte.';
  END IF;
END $$;
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('24d1e958-c82f-46de-9ff2-4ca64caf46e3', 'natursteinarbeiten', 'Natursteinarbeiten', 'Garten · Mauern', 'Zeitlose Eleganz aus der Natur – Mauern, Wege und Terrassen aus hochwertigem Naturstein.', 'Natursteinarbeiten verleihen jedem Garten Stil, Wertigkeit und Beständigkeit. Ob Natursteinmauer, Gartenweg, Granit-Terrasse oder Sandstein-Treppe – mit Naturstein entsteht ein harmonisches Zusammenspiel von Farbe, Struktur und Form, das Ihren Außenbereich unverwechselbar macht.

Mit handwerklicher Präzision und langjähriger Erfahrung im Garten- und Landschaftsbau gestalten wir Natursteinflächen, die Ästhetik und Funktion perfekt vereinen. Jeder Stein ist ein Unikat – robust, wetterbeständig und voller natürlicher Schönheit.

Wir setzen auf hochwertige Materialien wie Granit, Sandstein, Basalt und Kalkstein, die sowohl optisch als auch technisch überzeugen. Durch fachgerechte Verarbeitung und eine sorgfältige Untergrundvorbereitung schaffen wir langlebige Ergebnisse, die sich harmonisch in Ihre Gartenlandschaft einfügen.', NULL, 1, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('d3ac79b1-cc29-41be-9d20-aa79275982cb', 'gartengestaltung', 'Gartengestaltung', 'Garten · Planung', 'Ihr Traumgarten – individuell geplant, liebevoll gestaltet und nachhaltig umgesetzt.', 'Ein Garten ist weit mehr als nur eine grüne Fläche mit Pflanzen – er ist Ihr ganz persönlicher Rückzugsort, ein Ort der Ruhe, Inspiration und Erholung. Mit professioneller Gartengestaltung und individueller Gartenplanung verwandeln wir Ihre Außenanlage in eine harmonische Wohlfühloase, die perfekt zu Ihrem Lebensstil passt.

Mit kreativen Gartenideen, Liebe zum Detail und fachlicher Expertise gestalten wir Gärten, die zu jeder Jahreszeit begeistern. Ob moderner Stadtgarten, naturnahe Landschaft oder eleganter Rückzugsort – wir entwickeln ein Konzept, das Ihre Wünsche und Vorstellungen in ein stimmiges Gesamtbild bringt.

Dabei legen wir größten Wert auf Qualität und Nachhaltigkeit: sorgfältig ausgewählte Pflanzen, langlebige Materialien und eine harmonische Integration in die Umgebung sind für uns selbstverständlich.', NULL, 2, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('04bd4eb7-ae9c-48b8-9ab1-faa571500cee', 'pflasterarbeiten', 'Pflasterarbeiten', 'Garten · Wege & Terrassen', 'Präzise verlegt, perfekt gestaltet – Wege, Terrassen und Einfahrten von höchster Qualität.', 'Ein ansprechender Garten beginnt mit soliden Wegen, eleganten Terrassen und funktionalen Einfahrten. Professionell verlegte Pflastersteine verbinden Ästhetik mit Langlebigkeit und verleihen Ihrem Außenbereich Struktur, Charakter und Stil.

Mit hochwertigem Material, handwerklicher Präzision und einem Auge fürs Detail gestalten wir Pflasterflächen, die nicht nur schön aussehen, sondern auch den täglichen Belastungen standhalten. Ob Naturstein, Betonstein oder Klinker – wir finden die passende Lösung für Ihre Vorstellungen und Ihr Budget.

Unser Ziel ist es, dauerhafte und harmonische Ergebnisse zu schaffen. Dabei achten wir auf exakte Linienführung, fachgerechtes Gefälle und eine solide Untergrundvorbereitung.', NULL, 3, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('96830647-21ae-4d7f-80fb-ef222c40ff48', 'bewaesserungsanlagen', 'Bewässerungsanlagen', 'Garten · Automatisiert', 'Effiziente Wasserversorgung für gesunde Grünflächen – smart, automatisch, ressourcenschonend.', 'Eine zuverlässige Bewässerung ist entscheidend für das Wachstum und die Vitalität Ihres Gartens. Mit einer professionellen Bewässerungsanlage sorgen wir dafür, dass Rasen, Pflanzen und Beete immer optimal mit Wasser versorgt sind – automatisch und individuell abgestimmt.

Moderne Bewässerungssysteme sparen nicht nur Zeit und Wasser, sondern fördern auch die gleichmäßige Entwicklung Ihrer Pflanzen. Ob Tropfbewässerung, Versenkregner oder vollautomatische Steuerung – wir planen und installieren Anlagen, die sich perfekt an die Gegebenheiten Ihres Grundstücks anpassen.

Auf Wunsch integrieren wir smarte Steuerungssysteme, die sich per App oder Sensor automatisch an Wetter und Jahreszeit anpassen.', NULL, 4, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('70cce84b-4e32-41d5-ab98-327a5dd7c443', 'zaunarbeiten', 'Zaunarbeiten', 'Firmengelände · Sicherheit', 'Sichtschutz und Sicherheit mit Stil – Zäune und Tore aus Holz, Metall oder Stein.', 'Wir gestalten den perfekten Gartenraum – individuell angepasst an Ihren Lebensstil. Von dezenten Sichtschutzelementen bis zu repräsentativen Eingangstoren verbinden unsere Zaunanlagen Funktionalität mit hochwertiger Optik. Wir arbeiten mit Holz, Metall, Gabionen und Naturstein und planen jede Anlage genau auf Ihre baulichen Gegebenheiten zu.', NULL, 5, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('db70f41c-8605-4c2a-886d-bcfe7ef45a27', 'rasenanlagen', 'Rasenanlagen', 'Garten · Lebensqualität', 'Rollrasen und hochwertige Einsaat – sattes Grün, das Ihrem Garten Charakter gibt.', 'Ein gepflegter Rasen ist das Herzstück jedes Gartens. Wir bereiten den Untergrund fachgerecht vor, säen hochwertige Rasenmischungen oder verlegen Rollrasen – damit Ihr Garten in kürzester Zeit zu einem grünen Wohnzimmer wird. Auf Wunsch ergänzen wir die Anlage mit automatischer Bewässerung und Mähroboter-Integration.', NULL, 6, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('20dd39db-086d-45c4-8fb2-b95b024a5801', 'erdarbeiten', 'Erdarbeiten', 'Garten · Entsorgung', 'Die Grundlage für jedes Gartenprojekt – Geländemodellierung, Aushub und Bodenverbesserung.', 'Bevor ein Traumgarten entstehen kann, braucht es ein solides Fundament. Erdarbeiten bilden die Basis jeder erfolgreichen Gartengestaltung – ob für Wege, Terrassen, Teiche oder Pflanzflächen. Sie entscheiden über Stabilität, Entwässerung und die langfristige Qualität Ihres Gartens.

Mit modernster Technik, Fachwissen und präziser Planung sorgen wir dafür, dass Ihr Boden optimal vorbereitet ist. Wir modellieren Gelände, schaffen Ebenen, heben Teiche aus und führen Bodenverbesserungen durch.', NULL, 7, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.services (id, slug, title, category, short_text, long_text, hero_image, sort_order, active, created_at, updated_at) VALUES ('662e3a89-0f7c-452d-8c4e-c3827c450b37', 'entwaesserung', 'Entwässerung', 'Garten · Wassermanagement', 'Fachgerechte Ableitung von Regen- und Oberflächenwasser für dauerhaft trockene Anlagen.', 'Eine durchdachte Entwässerung schützt Ihren Garten und Ihr Gebäude vor Staunässe und Erosion. Wir planen und installieren Drainagen, Rigolen und Versickerungssysteme, die das Wasser dort hinleiten, wo es hingehört – effizient, unauffällig und langlebig.', NULL, 8, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.projects (id, title, service_id, location, description, images, featured, active, created_at, updated_at) VALUES ('15b97106-0428-4a3e-8d1c-071b14b87d24', 'Residenz am Mainufer', NULL, 'Heidelberg', 'Im Rahmen der Außenanlagen wurden ein moderner Pool fachgerecht errichtet und mit Naturstein verkleidet. Die Terrasse ist aus einem Holzdeck erstellt worden.', ARRAY[]::text[], true, true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.jobs (id, slug, title, description, requirements, location, employment_type, active, created_at, updated_at) VALUES ('eef8985e-067a-44d3-9d0a-24daab86d2d3', 'landschaftsgaertner-m-w-d', 'Landschaftsgärtner:in (m/w/d)', 'Wir suchen Verstärkung für unser Team in Hattersheim. Sie wirken an der Umsetzung anspruchsvoller Außenanlagen mit – von Naturstein über Pflasterarbeiten bis zu Bewässerungssystemen.', 'Abgeschlossene Ausbildung im Garten- und Landschaftsbau oder vergleichbar; handwerkliches Geschick; Führerschein Klasse B; Teamfähigkeit und Zuverlässigkeit.', 'Hattersheim am Main', 'Vollzeit', true, '2026-05-28T12:06:16.290116+00:00', '2026-05-28T12:06:16.290116+00:00');
INSERT INTO public.site_settings (key, value) VALUES ('tracking', '{"ga4":"","gtm":"","banner":{"title":"Cookies & Privatsphäre","description":"Wir verwenden Cookies, um unsere Website zu betreiben und – mit Ihrer Zustimmung – Reichweite zu messen. Technisch notwendige Cookies sind immer aktiv."},"tiktokId":"","metaPixel":"","customHead":"","linkedinId":"","anonymizeIp":true,"consentVersion":1}'::jsonb) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
COMMIT;
