-- Refresh only unchanged imported copy; retain later administrator edits.
begin;
update public.services set short_text='Mauern, Wege, Terrassen und Stufen aus Naturstein.',long_text='Naturstein lässt sich für Terrassen, Gartenwege, Mauern und Treppen einsetzen. Material, Oberfläche und Fugenbild stimmen wir auf die Nutzung und die Umgebung ab.

Wir besprechen mit Ihnen die gewünschte Gestaltung und prüfen den vorhandenen Untergrund. Zum Arbeitsumfang gehören je nach Vorhaben die Vorbereitung der Fläche, der Unterbau und die Verlegung oder der Mauerbau.' where slug='natursteinarbeiten' and short_text='Zeitlose Eleganz aus der Natur – Mauern, Wege und Terrassen aus hochwertigem Naturstein.' and long_text='Natursteinarbeiten verleihen jedem Garten Stil, Wertigkeit und Beständigkeit. Ob Natursteinmauer, Gartenweg, Granit-Terrasse oder Sandstein-Treppe – mit Naturstein entsteht ein harmonisches Zusammenspiel von Farbe, Struktur und Form, das Ihren Außenbereich unverwechselbar macht.

Mit handwerklicher Präzision und langjähriger Erfahrung im Garten- und Landschaftsbau gestalten wir Natursteinflächen, die Ästhetik und Funktion perfekt vereinen. Jeder Stein ist ein Unikat – robust, wetterbeständig und voller natürlicher Schönheit.

Wir setzen auf hochwertige Materialien wie Granit, Sandstein, Basalt und Kalkstein, die sowohl optisch als auch technisch überzeugen. Durch fachgerechte Verarbeitung und eine sorgfältige Untergrundvorbereitung schaffen wir langlebige Ergebnisse, die sich harmonisch in Ihre Gartenlandschaft einfügen.' returning slug;
update public.services set short_text='Gärten neu anlegen und bestehende Außenanlagen umgestalten.',long_text='Welche Bereiche nutzen Sie heute, und was soll sich ändern? Aus diesen Fragen entwickeln wir mit Ihnen die Aufteilung Ihres Gartens: Wege, Sitzplätze, Rasen und Pflanzflächen.

Wir berücksichtigen vorhandene Pflanzen, die Lage des Grundstücks und den späteren Pflegeaufwand. Auch einzelne Gartenbereiche können erneuert werden. Den genauen Umfang halten wir im Angebot fest.' where slug='gartengestaltung' and short_text='Ihr Traumgarten – individuell geplant, liebevoll gestaltet und nachhaltig umgesetzt.' and long_text='Ein Garten ist weit mehr als nur eine grüne Fläche mit Pflanzen – er ist Ihr ganz persönlicher Rückzugsort, ein Ort der Ruhe, Inspiration und Erholung. Mit professioneller Gartengestaltung und individueller Gartenplanung verwandeln wir Ihre Außenanlage in eine harmonische Wohlfühloase, die perfekt zu Ihrem Lebensstil passt.

Mit kreativen Gartenideen, Liebe zum Detail und fachlicher Expertise gestalten wir Gärten, die zu jeder Jahreszeit begeistern. Ob moderner Stadtgarten, naturnahe Landschaft oder eleganter Rückzugsort – wir entwickeln ein Konzept, das Ihre Wünsche und Vorstellungen in ein stimmiges Gesamtbild bringt.

Dabei legen wir größten Wert auf Qualität und Nachhaltigkeit: sorgfältig ausgewählte Pflanzen, langlebige Materialien und eine harmonische Integration in die Umgebung sind für uns selbstverständlich.' returning slug;
update public.services set short_text='Terrassen, Einfahrten und Wege mit passendem Unterbau.',long_text='Eine Terrasse wird anders beansprucht als eine befahrene Einfahrt. Deshalb stimmen wir Material und Unterbau auf die Nutzung der Fläche ab.

Zu den Arbeiten können Aushub, Tragschicht, Einfassungen, Verlegung und Verfugung gehören. Höhen und Gefälle werden zusammen mit der Entwässerung geplant. Vorhandenes Pflaster prüfen wir bei Bedarf auf eine mögliche Wiederverwendung.' where slug='pflasterarbeiten' and short_text='Präzise verlegt, perfekt gestaltet – Wege, Terrassen und Einfahrten von höchster Qualität.' and long_text='Ein ansprechender Garten beginnt mit soliden Wegen, eleganten Terrassen und funktionalen Einfahrten. Professionell verlegte Pflastersteine verbinden Ästhetik mit Langlebigkeit und verleihen Ihrem Außenbereich Struktur, Charakter und Stil.

Mit hochwertigem Material, handwerklicher Präzision und einem Auge fürs Detail gestalten wir Pflasterflächen, die nicht nur schön aussehen, sondern auch den täglichen Belastungen standhalten. Ob Naturstein, Betonstein oder Klinker – wir finden die passende Lösung für Ihre Vorstellungen und Ihr Budget.

Unser Ziel ist es, dauerhafte und harmonische Ergebnisse zu schaffen. Dabei achten wir auf exakte Linienführung, fachgerechtes Gefälle und eine solide Untergrundvorbereitung.' returning slug;
update public.services set short_text='Bewässerung für Rasen und Beete, passend zu Grundstück und Wasseranschluss.',long_text='Rasenflächen und Pflanzbeete haben unterschiedliche Anforderungen an die Bewässerung. Wir planen Regner oder Tropfleitungen passend zu den Flächen und dem vorhandenen Wasseranschluss.

Die Steuerung und die Aufteilung in Bewässerungsbereiche besprechen wir mit Ihnen. Bei der Übergabe erklären wir die Bedienung und die notwendigen Schritte zur Pflege der Anlage.' where slug='bewaesserungsanlagen' and short_text='Effiziente Wasserversorgung für gesunde Grünflächen – smart, automatisch, ressourcenschonend.' and long_text='Eine zuverlässige Bewässerung ist entscheidend für das Wachstum und die Vitalität Ihres Gartens. Mit einer professionellen Bewässerungsanlage sorgen wir dafür, dass Rasen, Pflanzen und Beete immer optimal mit Wasser versorgt sind – automatisch und individuell abgestimmt.

Moderne Bewässerungssysteme sparen nicht nur Zeit und Wasser, sondern fördern auch die gleichmäßige Entwicklung Ihrer Pflanzen. Ob Tropfbewässerung, Versenkregner oder vollautomatische Steuerung – wir planen und installieren Anlagen, die sich perfekt an die Gegebenheiten Ihres Grundstücks anpassen.

Auf Wunsch integrieren wir smarte Steuerungssysteme, die sich per App oder Sensor automatisch an Wetter und Jahreszeit anpassen.' returning slug;
update public.services set short_text='Zäune, Tore und Sichtschutz für Ihr Grundstück.',long_text='Ein Zaun grenzt das Grundstück ab, ein Sichtschutz schafft mehr Privatsphäre. Höhe, Material, Verlauf und mögliche Tore legen wir gemeinsam mit Ihnen fest.

Vor der Montage prüfen wir die örtlichen Gegebenheiten und den Untergrund. Grundstücksgrenzen und gegebenenfalls nötige Genehmigungen müssen vor dem Bau geklärt sein.' where slug='zaunarbeiten' and short_text='Sichtschutz und Sicherheit mit Stil – Zäune und Tore aus Holz, Metall oder Stein.' and long_text='Wir gestalten den perfekten Gartenraum – individuell angepasst an Ihren Lebensstil. Von dezenten Sichtschutzelementen bis zu repräsentativen Eingangstoren verbinden unsere Zaunanlagen Funktionalität mit hochwertiger Optik. Wir arbeiten mit Holz, Metall, Gabionen und Naturstein und planen jede Anlage genau auf Ihre baulichen Gegebenheiten zu.' returning slug;
update public.services set short_text='Rasenflächen vorbereiten, einsäen oder mit Rollrasen anlegen.',long_text='Für eine neue Rasenfläche bereiten wir zunächst den Boden vor. Anschließend wird die Fläche eingesät oder Rollrasen verlegt, je nach gewünschtem Ergebnis und Zeitrahmen.

Damit der Rasen anwachsen kann, sind Bewässerung und Pflege in der ersten Zeit besonders wichtig. Dazu besprechen wir die nächsten Schritte mit Ihnen.' where slug='rasenanlagen' and short_text='Rollrasen und hochwertige Einsaat – sattes Grün, das Ihrem Garten Charakter gibt.' and long_text='Ein gepflegter Rasen ist das Herzstück jedes Gartens. Wir bereiten den Untergrund fachgerecht vor, säen hochwertige Rasenmischungen oder verlegen Rollrasen – damit Ihr Garten in kürzester Zeit zu einem grünen Wohnzimmer wird. Auf Wunsch ergänzen wir die Anlage mit automatischer Bewässerung und Mähroboter-Integration.' returning slug;
update public.services set short_text='Aushub, Geländeanpassung und Bodenvorbereitung für Außenanlagen.',long_text='Erdarbeiten schaffen die Grundlage für Wege, Terrassen und Gartenflächen. Wir tragen Boden ab, passen Geländehöhen an und bereiten Flächen für die folgenden Arbeiten vor.

Zufahrt, Bodenverhältnisse, vorhandene Leitungen und die Menge des Aushubs bestimmen den Aufwand. Abtransport und Entsorgung werden im vereinbarten Arbeitsumfang berücksichtigt.' where slug='erdarbeiten' and short_text='Die Grundlage für jedes Gartenprojekt – Geländemodellierung, Aushub und Bodenverbesserung.' and long_text='Bevor ein Traumgarten entstehen kann, braucht es ein solides Fundament. Erdarbeiten bilden die Basis jeder erfolgreichen Gartengestaltung – ob für Wege, Terrassen, Teiche oder Pflanzflächen. Sie entscheiden über Stabilität, Entwässerung und die langfristige Qualität Ihres Gartens.

Mit modernster Technik, Fachwissen und präziser Planung sorgen wir dafür, dass Ihr Boden optimal vorbereitet ist. Wir modellieren Gelände, schaffen Ebenen, heben Teiche aus und führen Bodenverbesserungen durch.' returning slug;
update public.services set short_text='Regen- und Oberflächenwasser auf Ihrem Grundstück gezielt ableiten.',long_text='Wo sammelt sich Wasser, und wohin kann es abfließen? Diese Fragen stehen am Anfang einer Entwässerungsplanung. Je nach Grundstück kommen Rinnen, Abläufe oder Versickerungslösungen infrage.

Wir betrachten Höhen, Gefälle und Bodenverhältnisse zusammen mit den geplanten Flächen. Zulässige Anschlüsse und örtliche Vorgaben müssen vor der Ausführung geklärt werden.' where slug='entwaesserung' and short_text='Fachgerechte Ableitung von Regen- und Oberflächenwasser für dauerhaft trockene Anlagen.' and long_text='Eine durchdachte Entwässerung schützt Ihren Garten und Ihr Gebäude vor Staunässe und Erosion. Wir planen und installieren Drainagen, Rigolen und Versickerungssysteme, die das Wasser dort hinleiten, wo es hingehört – effizient, unauffällig und langlebig.' returning slug;
commit;
